"""initial migration

Revision ID: ba02073fb6f1
Revises: 5f543bdbd97b
Create Date: 2016-07-29 11:13:31.811558

"""

# revision identifiers, used by Alembic.
revision = 'ba02073fb6f1'
down_revision = '5f543bdbd97b'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('post2',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('body', sa.String(length=140), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('post2')
    ### end Alembic commands ###
